### ISSUE TITLE
Failure to start after install

### ISSUE THREAD

**Issue by eddiezane** [cockroachdb/homebrew-cockroach#7]
Appears to install and compile successfully but fails to start.

```
~ go version
go version go1.8 darwin/amd64

~ brew install cockroachdb/cockroach/cockroach
==> Installing cockroach from cockroachdb/cockroach
==> Downloading https://binaries.cockroachdb.com/cockroach-beta-20170330.src.tgz
Already downloaded: /Users/eddiezane/Library/Caches/Homebrew/cockroach-beta-20170330.tgz
==> make install
==> Caveats
......................................
==> Summary
🍺  /usr/local/Cellar/cockroach/beta-20170330: 5 files, 44.7MB, built in 4 minutes 7 seconds

~ cockroach start
[1]    81027 killed     cockroach start
```

On macOS 10.12.4 (16E195)

**Comment by benesch** [comment]
Hi @eddiezane, sorry you're running into this. Glad you're giving CockroachDB a spin nonetheless.

You wouldn't be running Xcode 8.3 by chance, would you? This command will tell you if you don't know offhand:

```
pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
```

This is almost certainly an unfortunate bug with the Go toolchain itself, which only presents if you compile with Xcode 8.3. If you're curious, the upstream issue is golang/go#19734. The most straightforward workaround is to use one of our [alternate installation methods](https://www.cockroachlabs.com/docs/install-cockroachdb.html) for now. The binaries should work unchanged; if you decide to build from source, you'll want to pass `GOFLAGS='-ldflags -s'` like so:

```shell
$ make build GOFLAGS=-'ldflags -s'
```

If you don't mind waiting, I'll open a PR shortly to ship a fix in this tap. Should merge later tonight or tomorrow.

Thanks again for the report!

**Comment by eddiezane** [comment]
@benesch thanks for the ludicrously quick and informative reply!

I am indeed on Xcode 8.3

```
~  pkgutil --pkg-info=com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 8.3.0.0.1.1490382677
volume: /
location: /
install-time: 1490812752
groups: com.apple.FindSystemFiles.pkg-group
```

I'll go with binary install for now.

Leaving issue open while a fix is pending but feel free to close.

Thanks again!

**Comment by benesch** [comment]
This tap now builds a binary that runs even when using Xcode 8.3! At least, it does on my machine—please don't hesitate to speak up if you're still having trouble.
